spring:
  application:
    name: BackendDietiEstates25

  datasource:
    url: jdbc:postgresql://database-dietiestates25.c5sk6gu40b1j.eu-north-1.rds.amazonaws.com:5432/dietiestates25?sslmode=require
    username: postgresDEM
    password: IngSw25!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "PROGETTO_ING_SW_DietiEstates25_SECRET_KEY!"
    expiration-ms: 3600000

server:
  port: 8080
